version: "3.7"

services:
  # image projectapp:
  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vite-react-ts-app
    ports:
      - '5173:5173'
    volumes:
    - ./frontend:/app
    - ./app/node_modules
    networks:
      - laravel

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./backend:/var/www:rw
    networks:
      - laravel

  # nginx
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - laravel

  # db mysql
  db:
    image: postgres 
    restart: always  
    environment:  
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scs 
    volumes:  
      - ./docker/dbdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
